ALTER TABLE CMPSTECH.EAC
 DROP PRIMARY KEY CASCADE;

DROP TABLE CMPSTECH.EAC CASCADE CONSTRAINTS;

CREATE TABLE CMPSTECH.EAC
(
  EAC_KEY          NUMBER(15)                   NOT NULL,
  EAC_SEQUENCE_NO  VARCHAR2(23 BYTE)            NOT NULL,
  FD_DESC_ID       VARCHAR2(4 BYTE)             NOT NULL,
  FD_NM            VARCHAR2(80 BYTE)            NOT NULL,
  TIC_PCT_1        NUMBER(9,6)                  NOT NULL,
  TC_PCT_1         NUMBER(9,6)                  NOT NULL,
  TER_PCT_1        NUMBER(9,6)                  NOT NULL,
  TIC_PCT_3        NUMBER(9,6)                  NOT NULL,
  TC_PCT_3         NUMBER(9,6)                  NOT NULL,
  TER_PCT_3        NUMBER(9,6)                  NOT NULL,
  TIC_PCT_5        NUMBER(9,6)                  NOT NULL,
  TC_PCT_5         NUMBER(9,6)                  NOT NULL,
  TER_PCT_5        NUMBER(9,6)                  NOT NULL,
  TIC_PCT_10       NUMBER(9,6)                  NOT NULL,
  TC_PCT_10        NUMBER(9,6)                  NOT NULL,
  TER_PCT_10       NUMBER(9,6)                  NOT NULL,
  IM_IMPL          NUMBER(9,6)                  NOT NULL,
  IM_UP            NUMBER(9,6)                  NOT NULL,
  OFFSHORE_FEE     NUMBER(9,6)                  NOT NULL,
  PERF_FEE         NUMBER(9,6)                  NOT NULL,
  LISP             NUMBER(9,6)                  NOT NULL,
  LC_FEE           NUMBER(9,6)                  NOT NULL,
  LC_PRICING       NUMBER(9,6)                  NOT NULL,
  BID_OFFER        NUMBER(9,6)                  NOT NULL,
  YIELD            NUMBER(9,6)                  NOT NULL,
  CLIENT_COST      NUMBER(9,6)                  NOT NULL,
  LIBERTY_COST     NUMBER(9,6)                  NOT NULL,
  DISC_COMM        VARCHAR2(1000 BYTE),
  COMMENTS         VARCHAR2(100 BYTE),
  EFF_DT           DATE                         NOT NULL,
  XPIR_DT          DATE,
  LAST_MOD_DT      DATE                         NOT NULL,
  LAST_MOD_USER    VARCHAR2(30 BYTE)            NOT NULL,
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS
)
TABLESPACE LIBDAT_S
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CMPSTECH.EAC_SEQUENCE_NO_INDX ON CMPSTECH.EAC
(EAC_SEQUENCE_NO)
LOGGING
TABLESPACE LIBIND_S
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX CMPSTECH.EAC_PK ON CMPSTECH.EAC
(EAC_KEY)
LOGGING
TABLESPACE LIBDAT_S
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160K
            NEXT             160K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM EAC FOR CMPSTECH.EAC;


ALTER TABLE CMPSTECH.EAC ADD (
  CONSTRAINT BID_OFFER_P
  CHECK (BID_OFFER<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT CLIENT_COST_P
  CHECK (CLIENT_COST<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT IM_IMPL_P
  CHECK (IM_IMPL<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT IM_UP_P
  CHECK (IM_UP<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT LC_FEE_P
  CHECK (LC_FEE<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT LC_PRICING_P
  CHECK (LC_PRICING<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT LIBERTY_COST_P
  CHECK (LIBERTY_COST<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT LISP_P
  CHECK (LISP<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT OFFSHORE_FEE_P
  CHECK (OFFSHORE_FEE<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT PERF_FEE_P
  CHECK (PERF_FEE<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TC_PCT_10_P
  CHECK (TC_PCT_10<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TC_PCT_1_P
  CHECK (TC_PCT_1<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TC_PCT_3_P
  CHECK (TC_PCT_3<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TC_PCT_5_P
  CHECK (TC_PCT_5<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TER_PCT_10_P
  CHECK (TER_PCT_10<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TER_PCT_1_P
  CHECK (TER_PCT_1<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TER_PCT_3_P
  CHECK (TER_PCT_3<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TER_PCT_5_P
  CHECK (TER_PCT_5<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TIC_PCT_10_P
  CHECK (TIC_PCT_10<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TIC_PCT_1_P
  CHECK (TIC_PCT_1<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TIC_PCT_3_P
  CHECK (TIC_PCT_3<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT TIC_PCT_5_P
  CHECK (TIC_PCT_5<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT YIELD_P
  CHECK (YIELD<= 100.00)
  ENABLE VALIDATE,
  CONSTRAINT EAC_PK
  PRIMARY KEY
  (EAC_KEY)
  USING INDEX CMPSTECH.EAC_PK
  ENABLE VALIDATE);

GRANT SELECT ON CMPSTECH.EAC TO CMPS_SELECT;

GRANT SELECT ON CMPSTECH.EAC TO COMPASS;

GRANT SELECT ON CMPSTECH.EAC TO COMPASS1;
